### ISSUE TITLE
Interrupts functions

### ISSUE THREAD

**Issue by satosystems** [ppelleti/hs-wiringPi#1]
Hello, @ppelleti 

I want to use your hs-wiringPi module on my job, because this module is good to my project. But there is missing features in this module that is interrupts functions, named `waitForInterrupt` and `wiringPiISR`.

I am ready to make a pull request about `wiringPiISR`. Can I make pull requests?

Thanks

**Comment by mignon-p** [comment]
Sure, feel free to make a pull request.  If it looks good, I will merge it.

I'm glad to hear you're finding hs-wiringPi useful!

**Comment by satosystems** [comment]
Okay, thank you.
